apiVersion: apps/v1
kind: Deployment
metadata:
  name: simplepay-db
  namespace: simplepay

spec:
  replicas: 1
  selector:
    matchLabels:
      app: simplepay-db
  template:
    metadata:
      labels:
        app: simplepay-db
    spec:
      containers:
      - name: postgres
        image: postgres:16
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_DB
          value: simplepay

        - name: POSTGRES_USER
          value: postgres

        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: simplepay-secrets
              key: DB_PASSWORD
        volumeMounts:
        - name: postgres-storage
          mountPath: /var/lib/postgresql/data

      volumes:
      - name: postgres-storage
        persistentVolumeClaim:
          claimName: simplepay-db-pvc
