apiVersion: v1
kind: Service
metadata:
  name: simplepay-backend
  namespace: simplepay
spec:
  selector:
    app: simplepay-backend
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000

